
"""web_sraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F05Zrgx_eYhgbTf2_3eX8w-HRJ0ydwXb
"""

!pip install bs4

!pip install requests

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

url = "https://www.amazon.in/s?k=heels+for+women&crid=258DREB995ODS&sprefix=heels%2Caps%2C222&ref=nb_sb_ss_ts-doa-p_3_5"

HEADERS = ({'User-Agent': 'https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes', 'Accept-Language':'en-US, en;q=0.5'})
response = requests.get(url, headers=HEADERS)

# response.content

soup = BeautifulSoup(response.content, "html.parser")
# soup

links = soup.find_all("a", attrs={'class':'a-link-normal s-no-outline'})
#links

# links[0]

link = links[0].get('href')

product_link = "https://amazon.in" + link
# product_link

new_response = requests.get(product_link,headers=HEADERS)
# new_response

new_soup = BeautifulSoup(new_response.content, "html.parser")
# new_soup

new_soup.find("span",attrs={'id':'productTitle'}).text.strip()

new_soup.find("span",attrs={'class':'a-offscreen'}).text.strip()